name: Mining
version: '1.0-SNAPSHOT'
main: org.desp.mining.Mining
api-version: '1.20'
depend: [Vault, MongoLibraryPlugin, BinggreAPI, BinggreEconomy, MMOCore]
commands:
  피로도확인:
    aliases: ["vlfhehghkrdls"]